### ISSUE TITLE
Project not working with Android Studio 2.3 or even 3.0

### ISSUE THREAD

**Issue by alaabualkheir** [Estimote/Android-Indoor-SDK#2]
Thank you for the much needed indoor solution for Android. However, I wasn't able to run it on neither Android Studio 2.3 nor 3.0. 
It says that the project "Does not use the Gradle build system. I tried using the import wizard but to no avail.
So, what shall I do to get this project running?

**Comment by pawelDylag** [comment]
Hello @alaabualkheir 

make sure you are using example app folder and not the main project folder (the one with README and CHANGELOG). It is obvious that it doesn't contain `build.gradle` file, so your Android studio can't recognize it as a Gradle project. Simply go to the example app subfolder (the one where `build.gradle` file is) and launch the project. 

Hope it helps :)
Cheers!

**Comment by alaabualkheir** [comment]
Thanks @pawelDylag , that did help and now the code is working.
