### ISSUE TITLE
Error when build Indoor-SDK for Android

### ISSUE THREAD

**Issue by vuongdnguyen** [Estimote/Android-Indoor-SDK#6]
When trying to build Indoor-SDK for Android. I got the error below. Can you help?

e: C:\Users\vuong\estimote\Android-Indoor-SDK-master\Android-Indoor-SDK-master\example\indoorapp\app\src\main\java\com\estimote\indoorapp\IndoorApplication.kt: (27, 74): Expecting an element
e: C:\Users\vuong\estimote\Android-Indoor-SDK-master\Android-Indoor-SDK-master\example\indoorapp\app\src\main\java\com\estimote\indoorapp\IndoorApplication.kt: (27, 103): Expecting an element
e: C:\Users\vuong\estimote\Android-Indoor-SDK-master\Android-Indoor-SDK-master\example\indoorapp\app\src\main\java\com\estimote\indoorapp\IndoorApplication.kt: (27, 55): Unresolved reference: YOUR
e: C:\Users\vuong\estimote\Android-Indoor-SDK-master\Android-Indoor-SDK-master\example\indoorapp\app\src\main\java\com\estimote\indoorapp\IndoorApplication.kt: (27, 64): Unresolved reference: ID
e: C:\Users\vuong\estimote\Android-Indoor-SDK-master\Android-Indoor-SDK-master\example\indoorapp\app\src\main\java\com\estimote\indoorapp\IndoorApplication.kt: (27, 81): Unresolved reference: YOUR
e: C:\Users\vuong\estimote\Android-Indoor-SDK-master\Android-Indoor-SDK-master\example\indoorapp\app\src\main\java\com\estimote\indoorapp\IndoorApplication.kt: (27, 90): Unresolved reference: TOKEN

**Comment by Mycek** [comment]
Hi @vuongdnguyen !
As indicated by the error you need to supply appId and appToken for your Cloud account. You can get it from:
https://cloud.estimote.com/#/apps

**Comment by vuongdnguyen** [comment]
It works. Thanks
