### ISSUE TITLE
onPositionOutsideLocation being called even inside the location

### ISSUE THREAD

**Issue by wjs9715** [Estimote/Android-Indoor-SDK#7]
Hello,

I have followed the step by step instruction to set up the indoor location.

While I am outside the location, it calls the onPositionOutsideLocation correctly,

but when I am inside the location, it calls both onPositionUpdate and onPositionOutsideLocation 

repeatedly. Is this normal behavior or an experimenting environment problem?

**Comment by pawelDylag** [comment]
Hello @wjs9715 !

This is not the correct behaviour. May I ask you for further details on this case? Is it always happening, or only when you re-visit your place? Also, may I ask you for phone details - model, OS version. 

Cheers!

**Comment by wjs9715** [comment]
@pawelDylag Thanks for the response,

I have tested with 2 different devices and the results were same

Sony F3113, Lenovo TB3-730F

Both running 6.0, compileSdkVersion 25

Also, it is always happening. Could this be problem with the beacon setup?

I am testing with 4 UWB beacons deployed to each corner of a 4m X 5m room.

**Comment by pawelDylag** [comment]
Hey @wjs9715 

This is awesome, thanks for the details! The bug was definitely in our SDK. I know what was the problem and the fix is scheduled for next release. Can't promise we will release new version today, but it's definitely a matter of few days 
Thanks a lot for reporting this 👍  - will notify you when new version is live.

**Comment by wjs9715** [comment]
Hello, @pawelDylag any updates on when the new release will be ready?

**Comment by pawelDylag** [comment]
Hey @wjs9715 - the new SDK version `2.0.0` is live. See the [CHANGELOG](https://github.com/Estimote/Android-Indoor-SDK/blob/master/CHANGELOG.md) to see the details. Your case shouldn't be a problem anymore :)

**Comment by wjs9715** [comment]
@pawelDylag 
Hey! Thanks for the new release!

Can you check if the repo is pushed to the maven or jcenter? 

It shows

Error:(30, 13) Failed to resolve: com.estimote:indoorsdk:2.0.0

**Comment by pawelDylag** [comment]
@wjs9715  - gosh, thanks for pointing this out. It seems that it's still pending in JCenter. Will notify you when it will be online :)

**Comment by pawelDylag** [comment]
Hey @wjs9715 - version `2.0.0` should be now accessible :)

**Comment by wjs9715** [comment]
@pawelDylag 
Hey, I just tested but seems still has issues. 

When I start positioning, onPositionOutsideLocation gets called once then nothing happens from there.

I compiled and tested with the example app also, but could not get it to work with both of device I mentioned above. It does not detects nor update the location.

Can you please check?

**Comment by pawelDylag** [comment]
Hey @wjs9715 

We are still working on underlying ScanningSDK (new in Indoor `2.0.0`) to handle as many phone models as possible. Couple of necessary questions to debug your problem (check on both phones):
1. Does your app have Location permissions enabled?
2. Does it have Bluetooth turned on?
3. What is your Beacon setup - is Estimote Location packet enabled? is iBeacon packet enabled?

Also, when launching positioning, could you check your log messages (no filters)? Android bluetooth stack should log any info about its status. Something like `ble: registered callback` or so. Could you send me those?

Although we are trying to test our new scanning mechanism on as many phones as possible, yours were not on the current priority list, so this is why we need to rely on your feedback for now :)
But don't worry, we will manage that! 💪

**Comment by wjs9715** [comment]
@pawelDylag 

Thx for the response

1. Yes, both of them has location permission.

2. Yes, both of them has Bluetooth turned on.

3. Yes, the beacons have location packet and iBeacon enabled.



`10-24 14:24:56.166 9592-9592/com.example.airport D/BluetoothAdapter: getLeState() returning 12
10-24 14:24:56.222 9592-9592/com.example.airport D/BluetoothAdapter: getLeState() returning 12
10-24 14:24:56.222 9592-9592/com.example.airport D/BluetoothAdapter: STATE_ON
10-24 14:24:56.225 9592-9592/com.example.airport D/BluetoothAdapter: getLeState() returning 12
10-24 14:24:56.230 9592-9605/com.example.airport D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
10-24 14:24:56.236 9592-9592/com.example.airport I/BluetoothLeScanner: startRegisteration: mLeScanClients={com.estimote.scanning_sdk.packet_provider.scanner.PostLollipopEstimoteScanner$scan$1$callback$1@6df36c8=android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper@66b7361}
10-24 14:24:56.246 9592-9592/com.example.airport D/BluetoothAdapter: getLeState() returning 12
10-24 14:24:56.247 9592-9592/com.example.airport D/BluetoothAdapter: STATE_ON
10-24 14:24:56.248 9592-9592/com.example.airport D/BluetoothAdapter: getLeState() returning 12
10-24 14:24:56.256 9592-9604/com.example.airport D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
10-24 14:24:56.263 9592-9592/com.example.airport I/BluetoothLeScanner: startRegisteration: mLeScanClients={com.estimote.scanning_sdk.packet_provider.scanner.PostLollipopEstimoteScanner$scan$1$callback$1@6edde86=android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper@eb8c347, com.estimote.scanning_sdk.packet_provider.scanner.PostLollipopEstimoteScanner$scan$1$callback$1@6df36c8=android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper@66b7361}
10-24 14:24:57.161 9592-9592/com.example.airport I/System.out: onPositionOutsideLocation called`

This is Bluetooth stack log

onPositionOutsideLocation gets called once and nothing happens from there.

**Comment by wjs9715** [comment]
@pawelDylag 
We found a device that works and its finally working!

Thanks for the help.

**Comment by KhaledAhmedS** [comment]
@wjs9715 
i face the same problem, can you tell me how did you solved it ?

**Comment by rusmichal** [comment]
Bump

**Comment by KhaledAhmedS** [comment]
@rusmichal  
is it must be indoor beacon (Location
UWB Beacon) or it can work with ble beacon(Location
BLE Beacon) ?
